name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read        # for checkout
  packages: write       # to push to GHCR

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (for arm64 builds on amd64 runners)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push multi-arch image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/manylinux-clang14:14.0.6
            ghcr.io/${{ github.repository_owner }}/manylinux-clang14:latest

      - name: Smoke-test image
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/manylinux-clang14:14.0.6 clang --version
